### ISSUE TITLE
TypeError in verbose

### ISSUE THREAD

**Issue by imyoric** [SadeghHayeri/GreenTunnel#196]
**Describe the bug**
Youtube still doesn't work. And TypeError in verbose mode.

**To Reproduce**
Run green-tunnel: `sudo green-tunnel --verbose 'green-tunnel:*'`

**Expected behavior**
Normal Working Green-tunnel

**Screenshots**
![image](https://github.com/user-attachments/assets/74d69250-af08-4893-a87d-963734d195f6)
Not exactly the same errors as in the context in log. But still identical.

**Desktop (please complete the following information):**
 - OS: macos sonoma (14.6.1)
 - Browser Chrome
 - Version - chrome: 128.0.6613.84, macos: 14.6.1

**Additional context**
Green-tunnel installed by using `sudo npm i -g green-tunnel`
Log:
```log
  green-tunnel:https-handler [HTTPS HELLO] www.google.com (length: 100) +0ms
  green-tunnel:https-handler [HTTPS HELLO] www.google.com (length: 100) +0ms
  green-tunnel:https-handler [HTTPS HELLO] www.google.com (length: 100) +0ms
  green-tunnel:https-handler [HTTPS HELLO] www.google.com (length: 100) +0ms
  green-tunnel:https-handler [HTTPS HELLO] www.google.com (length: 100) +0ms
  green-tunnel:https-handler [HTTPS HELLO] www.google.com (length: 88) +0ms
  green-tunnel:https-handler [HTTPS] receive from www.google.com (length: 1400) +139ms
  green-tunnel:https-handler [HTTPS] receive from www.google.com (length: 2800) +0ms
  green-tunnel:https-handler [HTTPS] receive from www.google.com (length: 1148) +0ms
  green-tunnel:https-handler [HTTPS] send to www.google.com (length: 74) +1ms
  green-tunnel:https-handler [HTTPS REQUEST] 149.154.167.223 +4s
  green-tunnel:dns [DNS] 149.154.167.223 -> 149.154.167.223 (1 ms) +4s
  green-tunnel:proxy TypeError: Invalid URL +10s
  green-tunnel:https-handler [HTTP REQUEST] 149.154.167.223 +0ms
  green-tunnel:https-handler [HTTP REQUEST] [2001:67c:4e8:f002::b] +1ms
  green-tunnel:dns TypeError: Cannot read properties of undefined (reading 'data')
  green-tunnel:dns     at DNSOverHTTPS._lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/https.js:15:28)
  green-tunnel:dns     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  green-tunnel:dns     at async DNSOverHTTPS.lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/base.js:28:10)
  green-tunnel:dns     at async createConnection (/usr/local/lib/node_modules/green-tunnel/src/utils/socket.js:7:13)
  green-tunnel:dns     at async handleHTTP (/usr/local/lib/node_modules/green-tunnel/src/handlers/http.js:20:23)
  green-tunnel:dns     at async Socket.<anonymous> (/usr/local/lib/node_modules/green-tunnel/src/handlers/request.js:20:7) +58ms
  green-tunnel:socket [Socket] connected to 149.154.167.223 (149.154.167.223) (101 ms) +4s
  green-tunnel:https-handler [HTTPS HELLO] 149.154.167.223 (length: 100) +103ms
  green-tunnel:https-handler [HTTPS HELLO] 149.154.167.223 (length: 100) +0ms
  green-tunnel:https-handler [HTTPS HELLO] 149.154.167.223 (length: 100) +0ms
  green-tunnel:https-handler [HTTPS HELLO] 149.154.167.223 (length: 13) +0ms
  green-tunnel:socket [Socket] connected to 149.154.167.223 (149.154.167.223) (102 ms) +3ms
  green-tunnel:dns TypeError: Cannot read properties of undefined (reading 'data')
  green-tunnel:dns     at DNSOverHTTPS._lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/https.js:15:28)
  green-tunnel:dns     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  green-tunnel:dns     at async DNSOverHTTPS.lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/base.js:28:10)
  green-tunnel:dns     at async createConnection (/usr/local/lib/node_modules/green-tunnel/src/utils/socket.js:7:13)
  green-tunnel:dns     at async handleHTTP (/usr/local/lib/node_modules/green-tunnel/src/handlers/http.js:20:23)
  green-tunnel:dns     at async Socket.<anonymous> (/usr/local/lib/node_modules/green-tunnel/src/handlers/request.js:20:7) +59ms
  green-tunnel:dns TypeError: Cannot read properties of undefined (reading 'data')
  green-tunnel:dns     at DNSOverHTTPS._lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/https.js:15:28)
  green-tunnel:dns     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  green-tunnel:dns     at async DNSOverHTTPS.lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/base.js:28:10)
  green-tunnel:dns     at async createConnection (/usr/local/lib/node_modules/green-tunnel/src/utils/socket.js:7:13)
  green-tunnel:dns     at async handleHTTP (/usr/local/lib/node_modules/green-tunnel/src/handlers/http.js:20:23)
  green-tunnel:dns     at async Socket.<anonymous> (/usr/local/lib/node_modules/green-tunnel/src/handlers/request.js:20:7) +61ms
  green-tunnel:dns TypeError: Cannot read properties of undefined (reading 'data')
  green-tunnel:dns     at DNSOverHTTPS._lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/https.js:15:28)
  green-tunnel:dns     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  green-tunnel:dns     at async DNSOverHTTPS.lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/base.js:28:10)
  green-tunnel:dns     at async createConnection (/usr/local/lib/node_modules/green-tunnel/src/utils/socket.js:7:13)
  green-tunnel:dns     at async handleHTTP (/usr/local/lib/node_modules/green-tunnel/src/handlers/http.js:20:23)
  green-tunnel:dns     at async Socket.<anonymous> (/usr/local/lib/node_modules/green-tunnel/src/handlers/request.js:20:7) +60ms
  green-tunnel:dns TypeError: Cannot read properties of undefined (reading 'data')
  green-tunnel:dns     at DNSOverHTTPS._lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/https.js:15:28)
  green-tunnel:dns     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  green-tunnel:dns     at async DNSOverHTTPS.lookup (/usr/local/lib/node_modules/green-tunnel/src/dns/base.js:28:10)
  green-tunnel:dns     at async createConnection (/usr/local/lib/node_modules/green-tunnel/src/utils/socket.js:7:13)
  green-tunnel:dns     at async handleHTTP (/usr/local/lib/node_modules/green-tunnel/src/handlers/http.js:20:23)
  green-tunnel:dns     at async Socket.<anonymous> (/usr/local/lib/node_modules/green-tunnel/src/handlers/request.js:20:7) +59ms
  green-tunnel:dns [DNS] cannot resolve hostname [2001:67c:4e8:f002::b] (Error: BAD IP FORMAT ([2001:67c:4e8:f002::b])) +0ms
  green-tunnel:cli:error AggregateError
  green-tunnel:cli:error     at internalConnectMultiple (node:net:1114:18)
  green-tunnel:cli:error     at afterConnectMultiple (node:net:1667:5) +0ms
  green-tunnel:https-handler [HTTPS] receive from 149.154.167.223 (length: 101) +249ms
```

**Comment by SadeghHayeri** [comment]
Hello, could you please confirm whether this bug still exists in version 3.0.5?
