### ISSUE TITLE
GreenTunnel doesn't work with adapters

### ISSUE THREAD

**Issue by Drun555** [SadeghHayeri/GreenTunnel#29]
**Describe the bug**
Hello. Welp, the bug is in the title. CLI crashes with that log: 
```
MBP-Andrei:~ drun$ gt
Error: Command failed: networksetup -setwebproxy '802.11n' 127.0.0.1 50646

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:203:13)
    at ChildProcess.EventEmitter.emit (domain.js:471:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 4,
  signal: null,
  cmd: "networksetup -setwebproxy '802.11n' 127.0.0.1 50646",
  stdout: '** Error: The parameters were not valid.\n',
  stderr: ''
}
```

Mojave 10.14.6
I'm using TP-LINK TL-WN725N, and they have their own software to connect via wi-fi, if this matters.

This is my network settings (output from ifconfig)

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC20: flags=0<> mtu 0
en0: flags=863<UP,BROADCAST,SMART,RUNNING,SIMPLEX> mtu 1500
	ether 11:22:33:44:55:66 
	inet 169.254.145.7 netmask 0xffff0000 broadcast 169.254.255.255
en2: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 50:3e:aa:85:e8:19 
	inet6 fe80::cbb:27ed:fa3b:7a69%en2 prefixlen 64 secured scopeid 0x6 
	inet 192.168.1.156 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::c8ee:f824:696d:1d9a%utun0 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>

```

**Comment by pcr910303** [comment]
@Drun555 I currently don't have any macOS machine available (I had some hardware problems a few days ago) so I can't give you much help, but...
Can you please execute `sh -c "networksetup -listnetworkserviceorder | grep \`route -n get 0.0.0.0 | grep 'interface' | cut -d ':' -f2\` -B 1 | head -n 1 | cut -d ' ' -f2"` and check if it's output is `802.11n`?
Does this match the Adaptor name denoted as `wifi` in the picture?
![wifiAdaptor](https://user-images.githubusercontent.com/938662/58366161-807f1980-7ee3-11e9-8d74-2085dafe0893.png)

**Comment by Drun555** [comment]
@pcr910303 it's not easy to use your head when you're not familiar with console or even with Mac.

My connection was named "802.11n NIC", not just "802.11n", so it was pretty clear for me at this stage. Renamed this, and now it's works.

**Comment by ibnuh** [comment]
@Drun555 I'm also using TP-LINK TL-WN725N, what thing I should rename? 
I've tried to rename the 'Service' on Settings > Adapter, still get the same error.

![Screen Shot 2019-09-08 at 16 44 37](https://user-images.githubusercontent.com/18393879/64486483-f7a0a980-d257-11e9-992c-9722d1040e74.png)

**Comment by Drun555** [comment]
@ibnuh rename "802.11n NIC" to "802.11n", and after it's should work.

**Comment by SadeghHayeri** [comment]
Is there still a problem in the new version?
