### ISSUE TITLE
Trouble with start on centos7

### ISSUE THREAD

**Issue by Alien-hide** [SadeghHayeri/GreenTunnel#36]
At  start on centos7:

[root@ ~]# gt --help
/usr/lib/node_modules/green-tunnel/bin/gt.js:66
async function main() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by SadeghHayeri** [comment]
Do you have this problem on the new version?

**Comment by Alien-hide** [comment]
The problem was in old node libraries.  fix it.  I will close issuance
