### ISSUE TITLE
CLI with Node not working on Systemd service

### ISSUE THREAD

**Issue by agungprabawa** [SadeghHayeri/GreenTunnel#65]
Hi, I'm try to use systemd for make green-tunnel auto start at start up by this code of systemd service. I'm was tested the ExecStart code working on terminal, but not when using systemd service

`[Unit]
Description=Green Tunnel

[Service]
ExecStart=/usr/bin/node /usr/lib/node_modules/green-tunnel/bin/gt.js

[Install]
WantedBy=multi-user.target`

but not working with error:
`Apr 29 23:14:22 linuxuser-GL552VX node[8898]:     at Proxy.join (path.js:1039:7)
Apr 29 23:14:22 linuxuser-GL552VX node[8898]:     at appData (/usr/lib/node_modules/green-tunnel/node_modules/app-data-folder/index.js:11:20)
Apr 29 23:14:22 linuxuser-GL552VX node[8898]:     at Object.<anonymous> (/usr/lib/node_modules/green-tunnel/src/utils/analytics.js:9:37)
Apr 29 23:14:22 linuxuser-GL552VX node[8898]:     at Generator.next (<anonymous>)
Apr 29 23:14:22 linuxuser-GL552VX node[8898]:     at Object.<anonymous> (/usr/lib/node_modules/green-tunnel/src/proxy.js:1)
Apr 29 23:14:22 linuxuser-GL552VX node[8898]:     at Generator.next (<anonymous>) {
Apr 29 23:14:22 linuxuser-GL552VX node[8898]:   code: 'ERR_INVALID_ARG_TYPE'
Apr 29 23:14:22 linuxuser-GL552VX node[8898]: }
`

**Comment by ardinusawan** [comment]
@agungprabawa you need to put argument. For instance
```
node ./bin/gt.js \
	--verbose $VERBOSE \
	--ip 0.0.0.0 \
	--port $PORT \
	--silent $SILENT \
	--system-proxy false \
	--dns-type $DNS_TYPE \
	--dns-server $DNS_SERVER
```

**Comment by RaminMT** [comment]
Hi
You may need to add `User=` to your systemd file
